module.exports = {  // safe to modify to suit your needs
    ', Noord-Brabant, Netherlands': '',
    ', Zeeland, Netherlands': '',
    ', Netherlands': '',
    ', Alabama, USA': ' (AL)',
    ', Alaska, USA': ' (AK)',
    ', American Samoa, USA': ' (AS)',
    ', Arizona, USA': ' (AZ)',
    ', Arkansas, USA': ' (AR)',
    ', California, USA': ' (CA)',
    ', Colorado, USA': ' (CO)',
    ', Connecticut, USA': ' (CT)',
    ', Delaware, USA': ' (DE)',
    ', District Of Columbia, USA': ' (DC)',
    ', Federated States Of Micronesia, USA': ' (FM)',
    ', Florida, USA': ' (FL)',
    ', Georgia, USA': ' (GA)',
    ', Guam, USA': ' (GU)',
    ', Hawaii, USA': ' (HI)',
    ', Idaho, USA': ' (ID)',
    ', Illinois, USA': ' (IL)',
    ', Indiana, USA': ' (IN)',
    ', Iowa, USA': ' (IA)',
    ', Kansas, USA': ' (KS)',
    ', Kentucky, USA': ' (KY)',
    ', Louisiana, USA': ' (LA)',
    ', Maine, USA': ' (ME)',
    ', Marshall Islands, USA': ' (MH)',
    ', Maryland, USA': ' (MD)',
    ', Massachusetts, USA': ' (MA)',
    ', Michigan, USA': ' (MI)',
    ', Minnesota, USA': ' (MN)',
    ', Mississippi, USA': ' (MS)',
    ', Missouri, USA': ' (MO)',
    ', Montana, USA': ' (MT)',
    ', Nebraska, USA': ' (NE)',
    ', Nevada, USA': ' (NV)',
    ', New Hampshire, USA': ' (NH)',
    ', New Jersey, USA': ' (NJ)',
    ', New Mexico, USA': ' (NM)',
    ', New York, USA': ' (NY)',
    ', North Carolina, USA': ' (NC)',
    ', North Dakota, USA': ' (ND)',
    ', Northern Mariana Islands, USA': ' (MP)',
    ', Ohio, USA': ' (OH)',
    ', Oklahoma, USA': ' (OK)',
    ', Oregon, USA': ' (OR)',
    ', Palau, USA': ' (PW)',
    ', Pennsylvania, USA': ' (PA)',
    ', Puerto Rico, USA': ' (PR)',
    ', Rhode Island, USA': ' (RI)',
    ', South Carolina, USA': ' (SC)',
    ', South Dakota, USA': ' (SD)',
    ', Tennessee, USA': ' (TN)',
    ', Texas, USA': ' (TX)',
    ', Utah, USA': ' (UT)',
    ', Vermont, USA': ' (VT)',
    ', Virgin Islands, USA': ' (VI)',
    ', Virginia, USA': ' (VA)',
    ', Washington, USA': ' (WA)',
    ', West Virginia, USA': ' (WV)',
    ', Wisconsin, USA': ' (WI)',
    ', Wyoming, USA': ' (WY)'
};